$(document).ready(function() {

    var icons = [];
    icons.push({'iconFilePath':'img/aldericon.png', 'iconValue':'aldericon'});
    icons.push({'iconFilePath':'img/aldericon_g.png', 'iconValue':'aldericon_g'});
    icons.push({'iconFilePath':'img/aldericon_r.png', 'iconValue':'aldericon_r'});
    icons.push({'iconFilePath':'img/aceicon.png', 'iconValue':'aceicon'});
    icons.push({'iconFilePath':'img/aceicong.png', 'iconValue':'aceicong'});
    icons.push({'iconFilePath':'img/anonicon.png', 'iconValue':'anonicon'});
    icons.push({'iconFilePath':'img/bloodstone.png', 'iconValue':'bloodstone'});
    icons.push({'iconFilePath':'img/bonaciuex_b.png', 'iconValue':'bonaciuex_b'});
    icons.push({'iconFilePath':'img/bonaciuex_g.png', 'iconValue':'bonaciuex_g'});
    icons.push({'iconFilePath':'img/boots1.png', 'iconValue':'boots1'});
    icons.push({'iconFilePath':'img/bullet_1.png', 'iconValue':'bullet_1'});
    icons.push({'iconFilePath':'img/candleofglory.png', 'iconValue':'candleofglory'});
    icons.push({'iconFilePath':'img/caticon.png', 'iconValue':'caticon'});
    icons.push({'iconFilePath':'img/chipsicon.png', 'iconValue':'chipsicon'});
    icons.push({'iconFilePath':'img/cigarette.png', 'iconValue':'cigarette'});
    icons.push({'iconFilePath':'img/comb.png', 'iconValue':'comb'});
    icons.push({'iconFilePath':'img/contributor.png', 'iconValue':'contributor'});
    icons.push({'iconFilePath':'img/crossicon.png', 'iconValue':'crossicon'});
    icons.push({'iconFilePath':'img/cruel.png', 'iconValue':'cruel'});
    icons.push({'iconFilePath':'img/curseicon.png', 'iconValue':'curseicon'});
    icons.push({'iconFilePath':'img/dominant.png', 'iconValue':'dominant'});
    icons.push({'iconFilePath':'img/dumbpotion.png', 'iconValue':'dumbpotion'});
    icons.push({'iconFilePath':'img/exploreicon.png', 'iconValue':'exploreicon'});
    icons.push({'iconFilePath':'img/fancyhat.png', 'iconValue':'fancyhat'});
    icons.push({'iconFilePath':'img/feet.png', 'iconValue':'footfetishicon'});
    icons.push({'iconFilePath':'img/fishbones.png', 'iconValue':'fishbones'});
    icons.push({'iconFilePath':'img/flute_b.png', 'iconValue':'flute_b'});
    icons.push({'iconFilePath':'img/flute_g.png', 'iconValue':'flute_g'});
    icons.push({'iconFilePath':'img/flute_r.png', 'iconValue':'flute_r'});
    icons.push({'iconFilePath':'img/fluteshirt.png', 'iconValue':'fluteshirt'});
    icons.push({'iconFilePath':'img/foxicon.png', 'iconValue':'foxicon'});
    icons.push({'iconFilePath':'img/gender.png', 'iconValue':'gender'});
    icons.push({'iconFilePath':'img/grissicong.png', 'iconValue':'grissicong'});
    icons.push({'iconFilePath':'img/grizzicon.png', 'iconValue':'grizzicon'});
    icons.push({'iconFilePath':'img/gropotion.png', 'iconValue':'gropotion'});
    icons.push({'iconFilePath':'img/guilticon.png', 'iconValue':'guilticon'});
    icons.push({'iconFilePath':'img/horseson.png', 'iconValue':'horseson'});
    icons.push({'iconFilePath':'img/inanimate.png', 'iconValue':'inanimate'});
    icons.push({'iconFilePath':'img/jack_b.png', 'iconValue':'jack_b'});
    icons.push({'iconFilePath':'img/jack_g.png', 'iconValue':'jack_g'});
    icons.push({'iconFilePath':'img/kind.png', 'iconValue':'kind'});
    icons.push({'iconFilePath':'img/leatherjacket.png', 'iconValue':'leatherjacket'});
    icons.push({'iconFilePath':'img/leonar_r.png', 'iconValue':'leonar_r'});
    icons.push({'iconFilePath':'img/lin_b.png', 'iconValue':'lin_b'});
    icons.push({'iconFilePath':'img/magicaxe.png', 'iconValue':'magicaxe'});
    icons.push({'iconFilePath':'img/magicboots.png', 'iconValue':'magicboots'});
    icons.push({'iconFilePath':'img/magichelm.png', 'iconValue':'magichelm'});
    icons.push({'iconFilePath':'img/mailboxicon.png', 'iconValue':'mailboxicon'});
    icons.push({'iconFilePath':'img/mayorb.png', 'iconValue':'mayorb'});
    icons.push({'iconFilePath':'img/mayorg.png', 'iconValue':'mayorg'});
    icons.push({'iconFilePath':'img/mikhail_b.png', 'iconValue':'mikhail_b'});
    icons.push({'iconFilePath':'img/mikhail_g.png', 'iconValue':'mikhail_g'});
    icons.push({'iconFilePath':'img/mrbat.png', 'iconValue':'mrbat'});
    icons.push({'iconFilePath':'img/muscat_1.png', 'iconValue':'muscat_1'});
    icons.push({'iconFilePath':'img/navigate_icon.png', 'iconValue':'navigate_icon'});
    icons.push({'iconFilePath':'img/nosering.png', 'iconValue':'nosering'});
    icons.push({'iconFilePath':'img/oldhat.png', 'iconValue':'oldhat'});
    icons.push({'iconFilePath':'img/oldsword.png', 'iconValue':'oldsword'});
    icons.push({'iconFilePath':'img/outcasticon.png', 'iconValue':'outcasticon'});
    icons.push({'iconFilePath':'img/painicon.png', 'iconValue':'painicon'});
    icons.push({'iconFilePath':'img/pawmusk.png', 'iconValue':'pawmusk'});
    icons.push({'iconFilePath':'img/pie_1.png', 'iconValue':'pie_1'});
    icons.push({'iconFilePath':'img/playericon.png', 'iconValue':'playericon'});
    icons.push({'iconFilePath':'img/prisonshirt.png', 'iconValue':'prisonshirt'});
    icons.push({'iconFilePath':'img/raccoonicon.png', 'iconValue':'raccoonicon'});
    icons.push({'iconFilePath':'img/robby_b.png', 'iconValue':'robby_b'});
    icons.push({'iconFilePath':'img/robby_g.png', 'iconValue':'robby_g'});
    icons.push({'iconFilePath':'img/rufo.png', 'iconValue':'rufo'});
    icons.push({'iconFilePath':'img/saberhagen_b.png', 'iconValue':'saberhagen_b'});
    icons.push({'iconFilePath':'img/saberhagen_g.png', 'iconValue':'saberhagen_g'});
    icons.push({'iconFilePath':'img/shrinkpotion.png', 'iconValue':'shrinkpotion'});
    icons.push({'iconFilePath':'img/size.png', 'iconValue':'size'});
    icons.push({'iconFilePath':'img/skullmask.png', 'iconValue':'skullmask'});
    icons.push({'iconFilePath':'img/smartpotion.png', 'iconValue':'smartpotion'});
    icons.push({'iconFilePath':'img/socks.png', 'iconValue':'socks'});
    icons.push({'iconFilePath':'img/speciesicon.png', 'iconValue':'speciesicon'});
    icons.push({'iconFilePath':'img/stoneshield.png', 'iconValue':'stoneshield'});
    icons.push({'iconFilePath':'img/submissive.png', 'iconValue':'submissive'});
    icons.push({'iconFilePath':'img/supplies.png', 'iconValue':'supplies'});
    icons.push({'iconFilePath':'img/suppliesg.png', 'iconValue':'suppliesg'});
    icons.push({'iconFilePath':'img/thefticon.png', 'iconValue':'thefticon'});
    icons.push({'iconFilePath':'img/thevoid.png', 'iconValue':'thevoid'});
    icons.push({'iconFilePath':'img/time.png', 'iconValue':'time'});
    icons.push({'iconFilePath':'img/transformation.png', 'iconValue':'tffetish'});
    icons.push({'iconFilePath':'img/turner_b.png', 'iconValue':'turner_b'});
    icons.push({'iconFilePath':'img/turner_g.png', 'iconValue':'turner_g'});
    icons.push({'iconFilePath':'img/uselessraccoon.png', 'iconValue':'uselessraccoon'});
    icons.push({'iconFilePath':'img/vore.png', 'iconValue':'vorefetish'});
    icons.push({'iconFilePath':'img/watercloth.png', 'iconValue':'watercloth'});
    icons.push({'iconFilePath':'img/watervine_1.png', 'iconValue':'watervine_1'});
    icons.push({'iconFilePath':'img/westwood.png', 'iconValue':'westwood'});
    icons.push({'iconFilePath':'img/wineicon_2.png', 'iconValue':'wineicon_2'});
    icons.push({'iconFilePath':'img/wineicon.png', 'iconValue':'wineicon'});
    icons.push({'iconFilePath':'img/witch_lotus.png', 'iconValue':'witch_lotus'});
    icons.push({'iconFilePath':'img/wolficon.png', 'iconValue':'wolficon'});

    function GenerateIconCss() {
        var style = document.createElement('style');
        style.type = 'text/css';
        for (var i = 0; i < icons.length; i++) {
            var BuildStyle = "."+icons[i].iconValue+ " {background-image: url(\""+icons[i].iconFilePath+"\");}";
            style.innerHTML+= BuildStyle;
        }
        //style.innerHTML = '.cssClass { color: #F00; }';
        document.getElementsByTagName('head')[0].appendChild(style);
    }
    GenerateIconCss();
});